[build]
  args_bin = []
  bin = "./bin/auth-service"
  cmd = "go build -o ./bin/auth-service ./cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "bin", "temp", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = "15s"
  log = "build-errors.log"
  poll = true
  poll_interval = 500
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true